[pytest]
python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*

markers =
    ui: Маркировка для регрессионных тестов UI.
    smoke: Маркировка для smoke тестов
    regression: Маркировка для регрессионных тестов.
    slow: Маркировка для медленныйх тестов
    authorization: Маркировка для тестов, связанных с авторизацией пользователей.
    critical: Маркировка для критичных кейсов
    registration: Маркировка для тестов проверяющих авторизацию



